[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://vowsyhnhbbhtzzrhfllp.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_1MqQvInXORC2GwBDCdyXYg_qJPSCChx"

[[plugins]]
  package = "@netlify/plugin-nextjs"
